### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by ethanrich** [vinothpandian/nasa-tlx-desktop#1]
Hello! I would love to use the desktop version, however my Windows 10 machine (meeting the requirements) doesn't run the executable.

**Comment by vinothpandian** [comment]
Try this version here [Windows 10](https://github.com/vinothpandian/nasa-tlx-desktop/releases/download/1.0.0/NasaTLX.Setup.1.0.0.exe)

**Comment by ethanrich** [comment]
Thanks very much! Also, is this app available in German?

Cheers,
Ethan

**Comment by vinothpandian** [comment]
Great! I am planning to add translations to other languages (probably next month). Would you be interested in helping?
